### Creates a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Sandro Henrique23",
  "email": "test23@example.com",
  "address":"123 Rua Doutora Mariana",
  "dateOfBirth": "2001-10-26",
  "registeredDate": "2024-11-28"
}

###