### Updates an existing entity
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Mariana Vasconcelosss",
  "email": "marianaa@example.com",
  "address":"123 Rua Doutor Sandro",
  "dateOfBirth": "2003-05-14"
}

###